#! /usr/bin/env sh
git clone http://github.com/wizardwerdna/wz-development-environment.git $1 &&
cd $1 &&
npm install &&
bower install &&
rm test/*.js app/*.js app/index.html app/styles/app.css &&
karma start
